version: "3"
services:
  postgres:
    image: mdillon/postgis:9.6-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weathersong
      POSTGRES_USER: weathersong
      POSTGRES_PASSWORD: weathersong
